---
- name: check if folder f1 is present if not create a file f1
  hosts: all
  tasks:
    - name: check for the folder f1
      stat: 
       path: /home/ubuntu/f1
      register: a
    - name: display output of the above modules
      debug:
        var: a
    - name: create file f1 if folder f1 is not present 
      file:
        name: /home/ubuntu/f1
        state: touch
      when: a.stat.exists == false
...
